### ISSUE TITLE
如何处理客户端ip和端口变化

### ISSUE THREAD

**Issue by LHRchina** [bilibili/quiche#17]
1.客户端网络发生变化,重建连接，在LB上根据connection ID做路由，保证转发到相同的实例上，LB如果是Nginx，是否也要修改Nginx？
2.这个仓库是一个单进程的实例，对于生产环境，也是要做一些修改？

**Comment by MacroLau** [comment]
1. 是的，quiche作为底层库，ngx需要做一个lb quic module来根据connection ID转发到对应的实例；
2. quiche作为底层库可以是单进程模式也可以类似于ngx的多进程模式；
