### ISSUE TITLE
simple_quic_client验证证书就会core dump

### ISSUE THREAD

**Issue by CChuancey** [bilibili/quiche#20]
![image](https://user-images.githubusercontent.com/37216768/205596043-5310db4e-3b2e-401b-b99d-9e52cbe95778.png)
![image](https://user-images.githubusercontent.com/37216768/205596142-c7e23c57-daab-4cf6-a563-0959ad089762.png)

**Comment by CChuancey** [comment]
这是gdb输出的调用堆栈
![image](https://user-images.githubusercontent.com/37216768/205596484-5498a204-4e93-49e1-b459-273b76bbed01.png)

**Comment by MacroLau** [comment]
simple_quic_client 目前不支持验证证书的功能

**Comment by ktprime** [comment]
gquic 本身证书校验逻辑非常难理解，服务器客户端如何实现和校验有点难度
iquic直接使用tls 就方便多了
