### ISSUE TITLE
關於 AF_XDP 的加速

### ISSUE THREAD

**Issue by kerwenwwer** [bilibili/quiche#22]
關於 AF_XDP 方面的實作是否有計劃放在這個 repo 下呢？

**Comment by cjcanbibi** [comment]
> 

目前，我们最新的版本已经实现了一个基于AF_XDP的batch writer，有兴趣的话可以查看。

**Comment by youguys** [comment]
> > 
> 
> 目前，我们最新的版本已经实现了一个基于AF_XDP的batch writer，有兴趣的话可以查看。

这个batch writer有怎么用的demo么，怎么改造simple_quic_server来实现AF_XDP

**Comment by zpeng2022** [comment]
@cjcanbibi 你好, 请问quiche的AF_XDP的实现, 是将一个socket 和网卡其中一个队列绑定吗？socket 数是根据网卡中队列的数量而定这样吗？

**Comment by cjcanbibi** [comment]
@zpeng2022 是的，可以这么使用。
