### ISSUE TITLE
ubuntu16.04编译失败,"error: function 'base::FilePath& base::FilePath::operator=(base::FilePath&&)' defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification '

### ISSUE THREAD

**Issue by zouzc** [bilibili/quiche#4]
编译环境: Release:        16.04
cmake:   3.20.4
commit: 21b1a63ead0a03497127d7f9ae74c3f0eed07e58
Merge: ce67509 d37d224
Author: wang_and_sheng <wangsheng@bilibili.com>
Date:   Mon May 24 13:51:23 2021 +0800

    Merge pull request #1 from incfex/main

    Update README.md

编译出错信息
[ 51%] Built target ssl
[ 51%] Building CXX object CMakeFiles/quiche.dir/base/files/file_path.cc.o
/home/quiche/base/files/file_path.cc:53:11: error: function 'base::FilePath& base::FilePath::operator=(base::FilePath&&)' defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ''
 FilePath& FilePath::operator=(FilePath&& that) noexcept = default;
           ^
CMakeFiles/quiche.dir/build.make:75: recipe for target 'CMakeFiles/quiche.dir/base/files/file_path.cc.o' failed
make[2]: *** [CMakeFiles/quiche.dir/base/files/file_path.cc.o] Error 1
CMakeFiles/Makefile2:813: recipe for target 'CMakeFiles/quiche.dir/all' failed

**Comment by wangsheng-bilibili** [comment]
编译器用的GCC什么版本？

**Comment by ktprime** [comment]
gcc version >= 9

**Comment by zouzc** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by ktprime** [comment]
@zouzc 升级编译器到至少7.5（9.x最好），16.04 自带的 gcc5.4 不能完整支持c++17

**Comment by wangsheng-bilibili** [comment]
是的，也可以改下代码，把这种 `=default` 语法改成`{}`形式。

**Comment by zouzc** [comment]
@ktprime 　谢谢,升级到9.1.0后，libquiche.a编译成功了．

**Comment by zouzc** [comment]
@ktprime @wangsheng-bilibili  编译simple_quic_server时出错，错误信息

//usr/lib/libtcmalloc_minimal.a(libtcmalloc_minimal_internal_la-static_vars.o): In function `_GLOBAL__sub_I_static_vars.cc':
(.text.startup+0x42): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
CMakeFiles/simple_quic_server.dir/build.make:306: recipe for target 'simple_quic_server' failed
make[2]: *** [simple_quic_server] Error 1
CMakeFiles/Makefile2:927: recipe for target 'CMakeFiles/simple_quic_server.dir/all' failed
make[1]: *** [CMakeFiles/simple_quic_server.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

## cmake .. 输出信息
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "2.6.1")
-- Version: 7.0.3
-- Build type:
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT

## libtcmalloc_minimal信息
root@92c852d2770c:/home/quiche# ls /usr/lib/libtcmalloc_minimal* -al
-rw-r--r-- 1 root root 349308 May  5  2017 /usr/lib/libtcmalloc_minimal.a
lrwxrwxrwx 1 root root     28 May  5  2017 /usr/lib/libtcmalloc_minimal.so -> libtcmalloc_minimal.so.4.2.6
lrwxrwxrwx 1 root root     28 May  5  2017 /usr/lib/libtcmalloc_minimal.so.4 -> libtcmalloc_minimal.so.4.2.6
-rw-r--r-- 1 root root 163240 May  5  2017 /usr/lib/libtcmalloc_minimal.so.4.2.6
-rw-r--r-- 1 root root 390530 May  5  2017 /usr/lib/libtcmalloc_minimal_debug.a
lrwxrwxrwx 1 root root     34 May  5  2017 /usr/lib/libtcmalloc_minimal_debug.so -> libtcmalloc_minimal_debug.so.4.2.6
lrwxrwxrwx 1 root root     34 May  5  2017 /usr/lib/libtcmalloc_minimal_debug.so.4 -> libtcmalloc_minimal_debug.so.4.2.6
-rw-r--r-- 1 root root 183784 May  5  2017 /usr/lib/libtcmalloc_minimal_debug.so.4.2.6

**Comment by wangsheng-bilibili** [comment]
1. 先不用tcmalloc库，cmake .. -DENABLE_LINK_TCMALLOC=off
2. 如果1可以，证明tcmalloc库版本可能不对

**Comment by cjcanbibi** [comment]
> @ktprime @wangsheng-bilibili 编译simple_quic_server时出错，错误信息
> 
> //usr/lib/libtcmalloc_minimal.a(libtcmalloc_minimal_internal_la-static_vars.o): In function `_GLOBAL__sub_I_static_vars.cc': (.text.startup+0x42): undefined reference to `pthread_atfork'
> collect2: error: ld returned 1 exit status
> CMakeFiles/simple_quic_server.dir/build.make:306: recipe for target 'simple_quic_server' failed
> make[2]: *** [simple_quic_server] Error 1
> CMakeFiles/Makefile2:927: recipe for target 'CMakeFiles/simple_quic_server.dir/all' failed
> make[1]: *** [CMakeFiles/simple_quic_server.dir/all] Error 2
> Makefile:90: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> ## cmake .. 输出信息
> -- The C compiler identification is GNU 9.1.0
> -- The CXX compiler identification is GNU 9.1.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/g++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "2.6.1")
> -- Version: 7.0.3
> -- Build type:
> -- CXX_STANDARD: 17
> -- Performing Test has_std_17_flag
> -- Performing Test has_std_17_flag - Success
> -- Performing Test has_std_1z_flag
> -- Performing Test has_std_1z_flag - Success
> -- Performing Test SUPPORTS_USER_DEFINED_LITERALS
> -- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
> -- Performing Test FMT_HAS_VARIANT
> 
> ## libtcmalloc_minimal信息
> root@92c852d2770c:/home/quiche# ls /usr/lib/libtcmalloc_minimal* -al
> -rw-r--r-- 1 root root 349308 May 5 2017 /usr/lib/libtcmalloc_minimal.a
> lrwxrwxrwx 1 root root 28 May 5 2017 /usr/lib/libtcmalloc_minimal.so -> libtcmalloc_minimal.so.4.2.6
> lrwxrwxrwx 1 root root 28 May 5 2017 /usr/lib/libtcmalloc_minimal.so.4 -> libtcmalloc_minimal.so.4.2.6
> -rw-r--r-- 1 root root 163240 May 5 2017 /usr/lib/libtcmalloc_minimal.so.4.2.6
> -rw-r--r-- 1 root root 390530 May 5 2017 /usr/lib/libtcmalloc_minimal_debug.a
> lrwxrwxrwx 1 root root 34 May 5 2017 /usr/lib/libtcmalloc_minimal_debug.so -> libtcmalloc_minimal_debug.so.4.2.6
> lrwxrwxrwx 1 root root 34 May 5 2017 /usr/lib/libtcmalloc_minimal_debug.so.4 -> libtcmalloc_minimal_debug.so.4.2.6
> -rw-r--r-- 1 root root 183784 May 5 2017 /usr/lib/libtcmalloc_minimal_debug.so.4.2.6

我们建议tcmalloc库，也就是gperftools的版本选择2.7，可以试一下

**Comment by zouzc** [comment]
@wangsheng-bilibili 使用"cmake .. -DENABLE_LINK_TCMALLOC=off",编译成功
@cjcanbibi 使用gperftools2.7,不禁用DENABLE_LINK_TCMALLOC编译成功
