### ISSUE TITLE
Unable to use SSLKEYLOGFILE option

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [bilibili/quiche#8]
As i wanted to look at the decrypted packets using wireshark, i tried using the below:

`export SSLKEYLOGFILE=<quic_keylog_file>`, which should work for boring ssl
https://github.com/google/boringssl/search?q=SSLKEYLOGFILE&type=code

But it didn't work and i didn't get the keylog file.

Should we change the cmake file to include boringssl `tool/client.cc` to make it work and obtain SSLKEYLOGFILE?

**Comment by MacroLau** [comment]
You can use SSL_CTX_set_keylog_callback to generate keylog. For example:
![image2021-4-14_16-26-50](https://user-images.githubusercontent.com/27988149/134473302-d76d10d2-f103-4b87-a71b-0386c4fe1168.png)

**Comment by deshmukhrajvardhan** [comment]
Thank you @MacroLau  for the above. It works well! I'll go ahead and and give an option to specify the filename to write into as well.

**Comment by soumyajit0** [comment]
@MacroLau This works well when we haven't specified the server's quick version. Once I use the `--quic_versions="h3-Q043"` no logs are generated. Do you know why?
